// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3b8k_WRuBOyt0Rj0GCpfw43r7cGZsuww',
    appId: '1:314550447841:web:38e5ffe4e7df9358db51a0',
    messagingSenderId: '314550447841',
    projectId: 'dine-drop-3b3c2',
    authDomain: 'dine-drop-3b3c2.firebaseapp.com',
    storageBucket: 'dine-drop-3b3c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAMPNdCQoZw2QzdHj5aa1Mqyi6QvVw1s',
    appId: '1:314550447841:android:0b32ec88ef347d2fdb51a0',
    messagingSenderId: '314550447841',
    projectId: 'dine-drop-3b3c2',
    storageBucket: 'dine-drop-3b3c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTgWMcRveNsiWspR_DApIErTG9EHFQaKY',
    appId: '1:314550447841:ios:5417f40d874350ebdb51a0',
    messagingSenderId: '314550447841',
    projectId: 'dine-drop-3b3c2',
    storageBucket: 'dine-drop-3b3c2.firebasestorage.app',
    iosBundleId: 'com.codexia.dineDrop',
  );
}
